#!/bin/sh
# TODO:
#       - Allow the ability to specify a specific server within the specified city code
#
#       - Provide a general menu for choosing between different
#           - Allow the ability to switch between wireguard and openvpn

FZFMULLVAD_RUNTIME_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/fzfmullvad"

if command -v highlight >/dev/null; then
    markup_command="highlight -O ansi --syntax yaml"
elif command -v pygmentize >/dev/null; then
    markup_command="pygmentize -f terminal -l yaml"
else
    markup_command="more"
fi

if [ -e "$FZFMULLVAD_RUNTIME_DIR/lastupdate" ];then
    if [ "$(date +%x)" != "$(cat "$FZFMULLVAD_RUNTIME_DIR/lastupdate")" ]; then
        mullvad relay update
        date +%x > "$FZFMULLVAD_RUNTIME_DIR/lastupdate"
    fi
else
    mullvad relay update
    date +%x > "$FZFMULLVAD_RUNTIME_DIR/lastupdate"
fi

main(){
    country_code=$(
        mullvad relay list |
        grep -v '-' |
        grep -v '@' |
        sed '/^\s*$/d' |
        fzf --preview="mullvad status -l | $markup_command" |
        # fzf --preview="mullvad relay list | awk "/$(echo {} | tr ' ' '\n' | tail -1)/"" |
        awk -F'(' '{print $2}' |
        sed 's|)||'
    )

    [ -z "$country_code" ] && echo "No country specified" && exit 130

    city_code=$(
        mullvad relay list |
        awk "/\($country_code\)/,/^$/" |
        awk -F'@' '/@/{print $1}' |
        fzf |
        awk -F'(' '{print $2}' |
        awk -F')' '{print $1}'
    )

    [ -z "$city_code" ] && main

    mullvad relay set location \
        "$country_code" \
        "$city_code"
}

main

mullvad status | grep -q Disconnected && mullvad connect

# Prevent timeout
sleep 0.1

while mullvad status | grep -q 'Connecting\|Disconnecting\|Disconnected'; do
    notify-send -i "${XDG_DATA_HOME:-$HOME/.local/share}/fzfmullvad/mullvad.png" \
        -h string:x-canonical-private-synchronous:fzfmullvad \
        "$(mullvad status -l)"
    sleep 1
done

notify-send -i "${XDG_DATA_HOME:-$HOME/.local/share}/fzfmullvad/mullvad.png" \
    -h string:x-canonical-private-synchronous:fzfmullvad \
    "$(mullvad status -l)"
