#!/bin/sh
# TODO:
#       - Allow the ability to specify a specific server within the specified city code
#
#       - Provide a general menu for choosing between different
#           - Allow the ability to switch between wireguard and openvpn

# TODO: 
#      - Add notifications

main(){
    country_code=$(\
        mullvad relay list |
        grep -v '-' |
        grep -v '@' |
        sed '/^\s*$/d' |
        fzf |
        awk -F'(' '{print $2}' |
        sed 's|)||'
    )

    [ -z "$country_code" ] && echo "No country specified" && exit 1

    server_code=$(\
        mullvad relay list |
        awk "/\($country_code\)/,/^$/" |
        awk -F'@' '/@/{print $1}' |
        fzf |
        awk -F'(' '{print $2}' |
        awk -F')' '{print $1}'
    )

    [ -z "$server_code" ] && main

    mullvad relay set location \
        "$country_code" \
        "$server_code"
}

main
